"""Public pure-domain facade for immutable discharge fragments."""

from src.domain.fragment_builder import (
    build_discharge_fragment_profiles,
    truncate_discharge_fragment_profiles,
)
from src.domain.fragment_primitives import (
    MAX_COMPACT_DESCRIPTORS,
    MAX_CONTRIBUTING_HASHES,
    MAX_MONOTONIC_NS,
    MAX_PHYSICAL_SAMPLES,
    MAX_PROFILE_ISSUES,
    MAX_PROFILE_RECORDS,
    MAX_SPANS_PER_SLICE,
    UINT64_MAX,
    AnchorKind,
    AnchorProvenance,
    ReadinessProvenance,
)
from src.domain.fragment_values import (
    CanonicalDischargeSample,
    CanonicalSampleSpan,
    DischargeFragmentProfile,
    DischargeSlice,
    EndpointAnchor,
    LoadStepObservation,
    ObservationOrigin,
    OmittedFragmentKind,
    ProfileReason,
    StartReadinessContext,
    build_canonical_sample_span,
    validate_canonical_sample_span,
)

__all__ = [
    "AnchorKind",
    "AnchorProvenance",
    "CanonicalDischargeSample",
    "CanonicalSampleSpan",
    "DischargeFragmentProfile",
    "DischargeSlice",
    "EndpointAnchor",
    "LoadStepObservation",
    "ObservationOrigin",
    "OmittedFragmentKind",
    "ProfileReason",
    "ReadinessProvenance",
    "StartReadinessContext",
    "build_canonical_sample_span",
    "build_discharge_fragment_profiles",
    "truncate_discharge_fragment_profiles",
    "validate_canonical_sample_span",
    "MAX_CONTRIBUTING_HASHES",
    "MAX_COMPACT_DESCRIPTORS",
    "MAX_MONOTONIC_NS",
    "MAX_PHYSICAL_SAMPLES",
    "MAX_PROFILE_ISSUES",
    "MAX_PROFILE_RECORDS",
    "MAX_SPANS_PER_SLICE",
    "UINT64_MAX",
]
